mysql: # You need to fill in your MySQL database details in here
  host: "localhost" # Set your host here.
  port: "3306" # This is the usual port for MySQL
  database: "ultimatehoppers" # The name of the database you want the plugin to use
  username: "root" # A username to access your database
  password: "" # A password to access your database


messages:
  not_player: "§c[UltimateHoppers] This command can only be run by a player"
  nai: "§c[UltimateHoppers] Please enter the name of an item"

vacuum:
  size: 9
  title: Vacuum Hopper
  delay:
    1: 8
    2: 6
    3: 3
    4: 1
  radius:
    1: GRAY 5
    2: GRAY 10
    3: GRAY 15
    4: GRAY 20
  slots:
    4:
      item: LIME_STAINED_GLASS_PANE
      name: Enabled
      type: general
      interact: toggle
      toggle:
        item: RED_STAINED_GLASS_PANE
        name: Disabled
    5:
      item: CHEST
      name: Vacuum Hopper
      type: info
      interact: upgrade
      delay:
        1: 8
        2: 6
        3: 3
        4: 1
      p1: Speed
      p2: Radius
      info:
        Enabled:
          1: GREEN Yes
          2: RED No
        Filtered:
          1: GREEN Yes
          2: RED No
        Speed:
          1: GRAY Slow
          2: GREEN Normal
          3: GOLD Speedy
          4: LIGHT_PURPLE Lightning
        Radius:
          1: GRAY 5
          2: GRAY 10
          3: GRAY 15
          4: GRAY 20
        Cost:
          1: YELLOW $1000
          2: YELLOW $4000
          3: YELLOW $9000
          4: YELLOW $16000
          5: YELLOW $25000
          6: YELLOW $36000
line:
  size: 9
  title: Hopper Line
  slots:
    3:
      item: LIME_STAINED_GLASS_PANE
      name: Enabled
      type: general
      interact: toggle
      toggle:
        item: RED_STAINED_GLASS_PANE
        name: Disabled
    5:
      item: CHEST
      name: Hopper Line
      type: info
      interact: upgrade
    7:
      item: COMPASS
      name: Facing
      type: list
      interact: switch-list
      names:
        - North
        - East
        - South
        - West
crates:
  header:
    4:
      item: LIME_STAINED_GLASS_PANE
      name: Enabled
      type: general
      interact: toggle
      toggle:
        item: RED_STAINED_GLASS_PANE
        name: Disabled
    5:
      item: CHEST
      name: Hopper Line
      type: info
      interact: upgrade
    6:
      item: NETHER_STAR
      name: Sell All
      type: button
      interact: sell-all
    10:
      item: BLACK_STAINED_GLASS_PANE
      name: ↑ Options ↓ Items
      type: filler
      interact: none
    11:
      item: BLACK_STAINED_GLASS_PANE
      name: ↑ Options ↓ Items
      type: filler
      interact: none
    12:
      item: BLACK_STAINED_GLASS_PANE
      name: ↑ Options ↓ Items
      type: filler
      interact: none
    13:
      item: BLACK_STAINED_GLASS_PANE
      name: ↑ Options ↓ Items
      type: filler
      interact: none
    14:
      item: BLACK_STAINED_GLASS_PANE
      name: ↑ Options ↓ Items
      type: filler
      interact: none
    15:
      item: BLACK_STAINED_GLASS_PANE
      name: ↑ Options ↓ Items
      type: filler
      interact: none
    16:
      item: BLACK_STAINED_GLASS_PANE
      name: ↑ Options ↓ Items
      type: filler
      interact: none
    17:
      item: BLACK_STAINED_GLASS_PANE
      name: ↑ Options ↓ Items
      type: filler
      interact: none
    18:
      item: BLACK_STAINED_GLASS_PANE
      name: ↑ Options ↓ Items
      type: filler
      interact: none
  small:
    size: 27
  medium:
    size: 36
  huge:
    size: 45